
INSERT INTO series (title, author_id, subgenre_id) VALUES ('this is it', 1, 2); 
INSERT INTO series (title, author_id, subgenre_id) VALUES ('this is it', 1, 2); 
INSERT INTO books (title, year, series_id) VALUES ('some book', 2002, 5); 
INSERT INTO books (title, year, series_id) VALUES ('some book', 2002, 5); 
INSERT INTO books (title, year, series_id) VALUES ('some book', 2002, 5); 
INSERT INTO books (title, year, series_id) VALUES ('some book', 2002, 5); 
INSERT INTO books (title, year, series_id) VALUES ('some book', 2002, 5); 
INSERT INTO books (title, year, series_id) VALUES ('some book', 2002, 5); 
INSERT INTO characters (name, species, motto, author_id) VALUES ('somehting', 'human', 'let go', 1); 
INSERT INTO characters (name, species, motto, author_id) VALUES ('somehting', 'human', 'let go', 1); 
INSERT INTO characters (name, species, motto, author_id) VALUES ('somehting', 'human', 'let go', 1); 
INSERT INTO characters (name, species, motto, author_id) VALUES ('somehting', 'human', 'let go', 1); 
INSERT INTO characters (name, species, motto, author_id) VALUES ('somehting', 'human', 'let go', 1); 
INSERT INTO characters (name, species, motto, author_id) VALUES ('somehting', 'human', 'let go', 1); 
INSERT INTO characters (name, species, motto, author_id) VALUES ('somehting', 'human', 'let go', 1); 
INSERT INTO characters (name, species, motto, author_id) VALUES ('somehting', 'human', 'let go', 1); 
INSERT INTO subgenres (name) VALUES ('comedy'); 
INSERT INTO subgenres (name) VALUES ('comedy'); 
INSERT INTO authors (name) VALUES ('Isaac'); 
INSERT INTO authors (name) VALUES ('Isaac'); 
INSERT INTO character_books (book_id, character_id) VALUES (1, 2); 
INSERT INTO character_books (book_id, character_id) VALUES (1, 2); 
INSERT INTO character_books (book_id, character_id) VALUES (1, 2); 
INSERT INTO character_books (book_id, character_id) VALUES (1, 2); 
INSERT INTO character_books (book_id, character_id) VALUES (1, 2); 
INSERT INTO character_books (book_id, character_id) VALUES (1, 2); 
INSERT INTO character_books (book_id, character_id) VALUES (1, 2); 
INSERT INTO character_books (book_id, character_id) VALUES (1, 2); 
INSERT INTO character_books (book_id, character_id) VALUES (1, 2); 
INSERT INTO character_books (book_id, character_id) VALUES (1, 2); 
INSERT INTO character_books (book_id, character_id) VALUES (1, 2); 
INSERT INTO character_books (book_id, character_id) VALUES (1, 2); 
INSERT INTO character_books (book_id, character_id) VALUES (1, 2); 
INSERT INTO character_books (book_id, character_id) VALUES (1, 2); 
INSERT INTO character_books (book_id, character_id) VALUES (1, 2);
INSERT INTO character_books (book_id, character_id) VAlUES (1, 2);